language: python

python:
  - "3.6"
  - "3.7"

dist: xenial

sudo: false

services:
  - docker

before_install:
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - export KEEPER_VERSION=v0.10.3
  - rm -rf "${HOME}/.ocean/keeper-contracts/artifacts"
  - bash -x start_ocean.sh --latest --no-brizo --no-faucet --no-secret-store --no-pleuston --local-spree-node 2>&1 > start_ocean.log &
  - docker stop ocean_aquarius_1
  - cd ..


# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis
script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    branch: master
    repo: oceanprotocol/aquarius
    python: 3.6

notifications:
   email: false
