version: '2.1'

services:
  mongodb:
    image: mongo:3.6
    ports:
    - "27017:27017"
    command: mongod
    networks:
    - backend

  keeper-contracts:
    image: oceanprotocol/keeper-contracts
    ports:
    - 8545:8545
    networks:
    - backend
    volumes:
    - ./../venv/contracts:/keeper-contracts/artifacts/

networks:
  backend:
